from pathlib import Path


page_path = Path('pages/pig-manager/index.html')
page = page_path.read_text(encoding='utf-8')

old_css = '''    .metric-viz{position:relative;height:44px;margin:7px 0 5px;opacity:.92}.metric-viz svg{display:block;width:100%;height:100%;overflow:visible}.spark-path{fill:none;stroke:var(--tone,var(--pink));stroke-width:2.35;stroke-linecap:round;stroke-linejoin:round}.spark-area{pointer-events:none}.spark-endpoint{fill:var(--surface-strong);stroke:var(--tone,var(--pink));stroke-width:2;vector-effect:non-scaling-stroke}.metric--trend .metric-context{margin-top:0;padding-top:7px}\n'''
new_css = '''    .metric-viz{position:relative;height:44px;margin:7px 0 5px;opacity:.94}.metric-viz svg{display:block;width:100%;height:100%;overflow:visible}.spark-path{fill:none;stroke:var(--tone,var(--pink));stroke-width:2.35;stroke-linecap:round;stroke-linejoin:round}.spark-area{pointer-events:none}.spark-endpoint{fill:var(--surface-strong);stroke:var(--tone,var(--pink));stroke-width:2;vector-effect:non-scaling-stroke}.metric--trend .metric-context{margin-top:auto;padding-top:7px}\n    .metric-meter,.metric-ruler{width:100%}.metric-meter-track{height:8px;margin-top:9px;border:1px solid color-mix(in srgb,var(--tone,var(--pink)) 18%,var(--line));border-radius:999px;background:color-mix(in srgb,var(--tone,var(--pink)) 8%,var(--surface-strong));overflow:hidden}.metric-meter-fill{display:block;width:0;height:100%;border-radius:inherit;background:linear-gradient(90deg,color-mix(in srgb,var(--tone,var(--pink)) 72%,white),var(--tone,var(--pink)));box-shadow:0 0 14px color-mix(in srgb,var(--tone,var(--pink)) 24%,transparent);transition:width .85s var(--ease)}.metric-viz-caption{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:7px;color:var(--muted);font-size:9px}.metric-viz-caption strong{color:var(--ink);font-size:10px;font-weight:820;font-variant-numeric:tabular-nums}\n    .metric-ruler-track{position:relative;height:5px;margin:14px 4px 8px;border-radius:999px;background:color-mix(in srgb,var(--tone,var(--blue)) 11%,var(--line));overflow:visible}.metric-ruler-fill{position:absolute;inset:0 auto 0 0;width:0;border-radius:inherit;background:linear-gradient(90deg,color-mix(in srgb,var(--tone,var(--blue)) 60%,white),var(--tone,var(--blue)));transition:width .85s var(--ease)}.metric-ruler-marker{position:absolute;top:50%;left:0;width:11px;height:11px;border:2px solid var(--surface-strong);border-radius:50%;background:var(--tone,var(--blue));box-shadow:0 0 0 3px color-mix(in srgb,var(--tone,var(--blue)) 14%,transparent);transform:translate(-50%,-50%);transition:left .85s var(--ease)}\n    .metric-rate{height:44px;display:flex;align-items:center;gap:10px}.metric-rate svg{width:42px;height:42px;flex:0 0 42px}.metric-rate-track,.metric-rate-arc{fill:none;stroke-width:5}.metric-rate-track{stroke:color-mix(in srgb,var(--tone,var(--plum)) 12%,var(--line))}.metric-rate-arc{stroke:var(--tone,var(--plum));stroke-linecap:round;filter:drop-shadow(0 0 5px color-mix(in srgb,var(--tone,var(--plum)) 24%,transparent));transition:stroke-dashoffset .9s var(--ease)}.metric-rate-copy{min-width:0;display:grid;gap:2px}.metric-rate-copy strong{font-size:11px;font-weight:820;color:var(--ink)}.metric-rate-copy span{font-size:9px;color:var(--muted)}.metric-viz-empty{height:44px;display:flex;align-items:center;color:var(--muted);font-size:9px}\n'''
if old_css not in page:
    raise SystemExit('metric visualization CSS anchor not found')
page = page.replace(old_css, new_css, 1)

replacements = {
'''      <div class="note">至少抽取过一次的去重玩家</div>\n      <div class="metric-context" id="cUsers">正在计算今日活跃占比…</div>''': '''      <div class="note">至少抽取过一次的去重玩家</div>\n      <div class="metric-viz metric-viz--meter" id="vUsers"></div>\n      <div class="metric-context" id="cUsers">正在计算今日活跃占比…</div>''',
'''      <div class="note">永久累计抽取次数</div>\n      <div class="metric-context" id="cDraws">正在计算近 14 日抽取…</div>''': '''      <div class="note">永久累计抽取次数</div>\n      <div class="metric-viz metric-viz--spark" id="vDraws"></div>\n      <div class="metric-context" id="cDraws">正在计算近 14 日抽取…</div>''',
'''      <div class="metric-viz" id="vToday"></div>''': '''      <div class="metric-viz metric-viz--spark" id="vToday"></div>''',
'''      <div class="note">每位玩家平均解锁的不同小猪</div>\n      <div class="metric-context" id="cAverage">正在计算图鉴探索空间…</div>''': '''      <div class="note">每位玩家平均解锁的不同小猪</div>\n      <div class="metric-viz metric-viz--ruler" id="vAverage"></div>\n      <div class="metric-context" id="cAverage">正在计算图鉴探索空间…</div>''',
'''      <div class="note">人均解锁 / 当前图鉴总数</div>\n      <div class="metric-context" id="cRate">正在计算收藏覆盖…</div>''': '''      <div class="note">人均解锁 / 当前图鉴总数</div>\n      <div class="metric-viz metric-viz--rate" id="vRate"></div>\n      <div class="metric-context" id="cRate">正在计算收藏覆盖…</div>''',
}
for old, new in replacements.items():
    if old not in page:
        raise SystemExit(f'KPI markup anchor not found: {old[:48]!r}')
    page = page.replace(old, new, 1)

anchor = 'function smoothLinePath(values,w,h,padX,padY,max,curve=.42){\n'
helpers = '''function renderMetricEmptyViz(id,label){const root=$(id);if(!root)return;root.setAttribute('aria-label',label);root.innerHTML=`<div class="metric-viz-empty">${esc(label)}</div>`}\nfunction renderMetricMeter(id,value,max,label){\n  const root=$(id);if(!root)return;const numerator=Math.max(0,Number(value)||0),denominator=Math.max(0,Number(max)||0),ratio=denominator>0?Math.max(0,Math.min(100,numerator/denominator*100)):0;root.setAttribute('aria-label',label);root.innerHTML=`<div class="metric-meter" role="img" aria-label="${esc(label)}"><div class="metric-meter-track"><span class="metric-meter-fill" data-width="${ratio.toFixed(3)}"></span></div><div class="metric-viz-caption"><span>今日活跃占累计用户</span><strong>${metricDecimal(ratio)}%</strong></div></div>`;requestAnimationFrame(()=>{const fill=root.querySelector('.metric-meter-fill');if(fill)fill.style.width=`${fill.dataset.width}%`})\n}\nfunction renderMetricRuler(id,value,max,label){\n  const root=$(id);if(!root)return;const current=Math.max(0,Number(value)||0),limit=Math.max(0,Number(max)||0),ratio=limit>0?Math.max(0,Math.min(100,current/limit*100)):0;root.setAttribute('aria-label',label);root.innerHTML=`<div class="metric-ruler" role="img" aria-label="${esc(label)}"><div class="metric-ruler-track"><span class="metric-ruler-fill" data-width="${ratio.toFixed(3)}"></span><i class="metric-ruler-marker" data-left="${ratio.toFixed(3)}"></i></div><div class="metric-viz-caption"><span>0</span><strong>${metricDecimal(current)} / ${limit.toLocaleString()}</strong><span>${limit.toLocaleString()}</span></div></div>`;requestAnimationFrame(()=>{const fill=root.querySelector('.metric-ruler-fill'),marker=root.querySelector('.metric-ruler-marker');if(fill)fill.style.width=`${fill.dataset.width}%`;if(marker)marker.style.left=`${marker.dataset.left}%`})\n}\nfunction renderMetricRate(id,percent,label){\n  const root=$(id);if(!root)return;const value=Math.max(0,Math.min(100,Number(percent)||0)),offset=100-value;root.setAttribute('aria-label',label);root.innerHTML=`<div class="metric-rate" role="img" aria-label="${esc(label)}"><svg viewBox="0 0 48 48" aria-hidden="true"><circle class="metric-rate-track" cx="24" cy="24" r="18"/><circle class="metric-rate-arc" cx="24" cy="24" r="18" pathLength="100" stroke-dasharray="100" stroke-dashoffset="100" transform="rotate(-90 24 24)" data-offset="${offset.toFixed(3)}"/></svg><div class="metric-rate-copy"><strong>${metricDecimal(value)}% 已覆盖</strong><span>${metricDecimal(100-value)}% 仍待探索</span></div></div>`;requestAnimationFrame(()=>{const arc=root.querySelector('.metric-rate-arc');if(arc)arc.style.strokeDashoffset=arc.dataset.offset})\n}\n'''
if anchor not in page:
    raise SystemExit('spark helper insertion anchor not found')
page = page.replace(anchor, helpers + anchor, 1)

old_render = '''function renderMetricVisuals(data){\n  const trend=Array.isArray(data.trend)?data.trend:[],metrics=data.metrics||{},users=trend.map(x=>Number(x.users)||0),draws=trend.map(x=>Number(x.draws)||0),today=Number(metrics.today_users)||0,totalUsers=Number(metrics.total_users)||0,catalog=Number(metrics.catalog_count)||0,averageUnlocked=Number(metrics.average_unlocked)||0,rate=Number(metrics.average_unlock_rate)||0;\n  const activeShare=totalUsers>0?today/totalUsers*100:0,totalDraws14=draws.reduce((sum,value)=>sum+value,0),avgDraws=draws.length?totalDraws14/draws.length:0,avgUsers=users.length?users.reduce((sum,value)=>sum+value,0)/users.length:0,previous=users.length>1?users[users.length-2]:null,delta=previous===null?null:today-previous,deltaPct=previous>0?delta/previous*100:null,remaining=Math.max(0,catalog-averageUnlocked);\n  metricContext('cUsers',`今日活跃 <strong>${today.toLocaleString()} 人</strong> · 占累计 <strong>${metricDecimal(activeShare)}%</strong>`);\n  metricContext('cDraws',`近 14 日 <strong>+${totalDraws14.toLocaleString()} 次</strong> · 日均 ${metricDecimal(avgDraws)}`);\n  if(delta===null)metricContext('cToday',`近 14 日日均 <strong>${metricDecimal(avgUsers)} 人</strong>`);\n  else{const cls=delta>0?'metric-up':delta<0?'metric-down':'metric-flat',sign=delta>0?'+':'';metricContext('cToday',`较昨日 <strong class="${cls}">${sign}${delta} 人${deltaPct===null?'':` · ${sign}${metricDecimal(deltaPct)}%`}</strong> · 14 日均 ${metricDecimal(avgUsers)}`)}\n  metricContext('cAverage',`图鉴 <strong>${catalog.toLocaleString()} 只</strong> · 人均尚未探索 ${metricDecimal(remaining)} 只`);\n  metricContext('cRate',`人均 <strong>${metricDecimal(averageUnlocked)} / ${catalog.toLocaleString()} 只</strong> · 按当前图鉴计算`);\n  renderSpark('vToday',users,3,'近 14 日每日活跃人数')\n}\n'''
new_render = '''function renderMetricVisuals(data){\n  const trend=Array.isArray(data.trend)?data.trend:[],metrics=data.metrics||{},users=trend.map(x=>Number(x.users)||0),draws=trend.map(x=>Number(x.draws)||0),today=Number(metrics.today_users)||0,totalUsers=Number(metrics.total_users)||0,totalDraws=Number(metrics.total_draws)||0,catalog=Number(metrics.catalog_count)||0,averageUnlocked=Number(metrics.average_unlocked)||0,rate=Number(metrics.average_unlock_rate)||0;\n  const activeShare=totalUsers>0?today/totalUsers*100:0,totalDraws14=draws.reduce((sum,value)=>sum+value,0),avgDraws=draws.length?totalDraws14/draws.length:0,avgUsers=users.length?users.reduce((sum,value)=>sum+value,0)/users.length:0,previous=users.length>1?users[users.length-2]:null,delta=previous===null?null:today-previous,deltaPct=previous>0?delta/previous*100:null,remaining=Math.max(0,catalog-averageUnlocked);\n  let runningDraws=Math.max(0,totalDraws-totalDraws14);const cumulativeDraws=draws.map(value=>(runningDraws+=value));\n  metricContext('cUsers',`今日活跃 <strong>${today.toLocaleString()} 人</strong> · 占累计 <strong>${metricDecimal(activeShare)}%</strong>`);\n  metricContext('cDraws',`近 14 日 <strong>+${totalDraws14.toLocaleString()} 次</strong> · 日均 ${metricDecimal(avgDraws)}`);\n  if(delta===null)metricContext('cToday',`近 14 日日均 <strong>${metricDecimal(avgUsers)} 人</strong>`);\n  else{const cls=delta>0?'metric-up':delta<0?'metric-down':'metric-flat',sign=delta>0?'+':'';metricContext('cToday',`较昨日 <strong class="${cls}">${sign}${delta} 人${deltaPct===null?'':` · ${sign}${metricDecimal(deltaPct)}%`}</strong> · 14 日均 ${metricDecimal(avgUsers)}`)}\n  metricContext('cAverage',`图鉴 <strong>${catalog.toLocaleString()} 只</strong> · 人均尚未探索 ${metricDecimal(remaining)} 只`);\n  metricContext('cRate',`人均 <strong>${metricDecimal(averageUnlocked)} / ${catalog.toLocaleString()} 只</strong> · 按当前图鉴计算`);\n  renderMetricMeter('vUsers',today,totalUsers,'今日活跃占累计用户比例');\n  if(cumulativeDraws.length)renderSpark('vDraws',cumulativeDraws,2,'近 14 日累计抽取轨迹');else renderMetricEmptyViz('vDraws','暂无 14 日抽取序列');\n  if(users.length)renderSpark('vToday',users,3,'近 14 日每日活跃人数');else renderMetricEmptyViz('vToday','暂无 14 日活跃序列');\n  renderMetricRuler('vAverage',averageUnlocked,catalog,'人均解锁相对当前图鉴规模');\n  renderMetricRate('vRate',rate,'平均收藏率覆盖进度')\n}\n'''
if old_render not in page:
    raise SystemExit('renderMetricVisuals anchor not found')
page = page.replace(old_render, new_render, 1)
page_path.write_text(page, encoding='utf-8')

test_path = Path('tests/test_admin_trend_ui_contract.py')
test = test_path.read_text(encoding='utf-8')
old_test = '''    assert "renderSpark('vDraws'" not in page\n    assert "renderSpark('vToday',users,3,'近 14 日每日活跃人数')" in page\n    for useful_copy in ("今日活跃", "占累计", "近 14 日", "较昨日", "人均尚未探索", "按当前图鉴计算"):\n        assert useful_copy in page\n'''
new_test = '''    for viz_id in ("vUsers", "vDraws", "vToday", "vAverage", "vRate"):\n        assert f'id="{viz_id}"' in page\n    assert "renderMetricMeter('vUsers',today,totalUsers" in page\n    assert "renderSpark('vDraws',cumulativeDraws,2,'近 14 日累计抽取轨迹')" in page\n    assert "renderSpark('vToday',users,3,'近 14 日每日活跃人数')" in page\n    assert "renderMetricRuler('vAverage',averageUnlocked,catalog" in page\n    assert "renderMetricRate('vRate',rate" in page\n    assert "totalDraws-totalDraws14" in page\n    for useful_copy in ("今日活跃", "占累计", "近 14 日", "较昨日", "人均尚未探索", "按当前图鉴计算"):\n        assert useful_copy in page\n'''
if old_test not in test:
    raise SystemExit('trend contract anchor not found')
test_path.write_text(test.replace(old_test, new_test, 1), encoding='utf-8')

browser_path = Path('tests/browser/admin-ui.test.mjs')
browser = browser_path.read_text(encoding='utf-8')
old_browser = '''  const spark = window.document.querySelector('#vToday .spark-path');\n  assert.ok(spark);\n  assert.match(spark.getAttribute('d'), / C /);\n  assert.equal(spark.getAttribute('d').includes(' L '), false);\n  assert.ok(window.document.querySelector('#vToday .spark-endpoint'));\n  assert.equal(window.document.querySelectorAll('.metric-snapshot-viz').length, 0);\n'''
new_browser = '''  assert.equal(window.document.querySelectorAll('#view-overview .metric-viz').length, 5);\n  assert.ok(window.document.querySelector('#vUsers .metric-meter-fill'));\n  const drawSpark = window.document.querySelector('#vDraws .spark-path');\n  assert.ok(drawSpark);\n  assert.match(drawSpark.getAttribute('d'), / C /);\n  assert.match(window.document.getElementById('vDraws').getAttribute('aria-label'), /累计抽取轨迹/);\n  const spark = window.document.querySelector('#vToday .spark-path');\n  assert.ok(spark);\n  assert.match(spark.getAttribute('d'), / C /);\n  assert.equal(spark.getAttribute('d').includes(' L '), false);\n  assert.ok(window.document.querySelector('#vToday .spark-endpoint'));\n  assert.ok(window.document.querySelector('#vAverage .metric-ruler-marker'));\n  assert.ok(window.document.querySelector('#vRate .metric-rate-arc'));\n  assert.equal(window.document.querySelectorAll('.metric-snapshot-viz').length, 0);\n'''
if old_browser not in browser:
    raise SystemExit('browser KPI test anchor not found')
browser_path.write_text(browser.replace(old_browser, new_browser, 1), encoding='utf-8')

changelog_path = Path('CHANGELOG.md')
changelog = changelog_path.read_text(encoding='utf-8')
old_changelog = '## 未發佈\n\n- 暫無。\n'
new_changelog = '''## 未發佈\n\n- 管理面板五張核心 KPI 補齊各自有語義的 mini visualization：總使用人數顯示今日活躍占累計用戶比例、累計抽取使用由永久總量錨定的近 14 日真實累計曲線、今日活躍保留每日活躍曲線、人均解鎖使用圖鑑尺度標尺、平均收藏率使用覆蓋率環形進度；不再靠同一組日活資料複製五條假趨勢。\n'''
if old_changelog not in changelog:
    raise SystemExit('CHANGELOG unreleased anchor not found')
changelog_path.write_text(changelog.replace(old_changelog, new_changelog, 1), encoding='utf-8')
